- packages/shared-memory-ring/shared-memory-ring.1.1.1/descr
- packages/shared-memory-ring/shared-memory-ring.1.1.1/findlib
- packages/shared-memory-ring/shared-memory-ring.1.1.1/opam
- packages/shared-memory-ring/shared-memory-ring.1.1.1/url
Signed-off-by: David Scott <dave.scott@citrix.com>
> Add shared-memory-ring.1.1.1

- packages/ctypes/ctypes.0.4.0/descr
- packages/ctypes/ctypes.0.4.0/opam
- packages/ctypes/ctypes.0.4.0/url
> Add git version of Ctypes.0.4.0

- packages/mirage-nat/mirage-nat.0.2/descr
- packages/mirage-nat/mirage-nat.0.2/opam
- packages/mirage-nat/mirage-nat.0.2/url
As requested by @avsm, add `mirage-nat` to available packages.
> add mirage-nat

- .travis-ci.sh
- .travis.yml
Travis tests *appear* to pass after this change, although submitting a PR with this title will surely jinx it.
> Fix travis

- packages/mirage-clock-unix/mirage-clock-unix.dev~mirage/opam
- packages/mirage-clock-xen/mirage-clock-xen.dev~mirage/opam
Sync opam files from mirage-clock repository.
> topkgd clocks

- .travis-ci.sh
My fault for not double-checking that Travis was doing the right thing. Much apologising.
> Fix Travis CI not honoring MODE setting

- packages/irmin/irmin.dev~mirage/descr
- packages/irmin/irmin.dev~mirage/opam
- packages/irmin/irmin.dev~mirage/url
for PCLOCK change; see mirage/irmin#367
> +irmin~dev.mirage

- .travis-ci.sh
- packages/datakit-client/datakit-client.dev~mirage/descr
- packages/datakit-client/datakit-client.dev~mirage/opam
- packages/datakit-client/datakit-client.dev~mirage/url
- packages/datakit-github/datakit-github.dev~mirage/descr
- packages/datakit-github/datakit-github.dev~mirage/opam
- packages/datakit-github/datakit-github.dev~mirage/url
- packages/datakit/datakit.dev~mirage/descr
- packages/datakit/datakit.dev~mirage/opam
- packages/datakit/datakit.dev~mirage/url
> add datakit trunk libraries

- .travis-ci.sh
- packages/datakit-client/datakit-client.dev~mirage/descr
- packages/datakit-client/datakit-client.dev~mirage/opam
- packages/datakit-client/datakit-client.dev~mirage/url
- packages/datakit-github/datakit-github.dev~mirage/descr
- packages/datakit-github/datakit-github.dev~mirage/opam
- packages/datakit-github/datakit-github.dev~mirage/url
- packages/datakit/datakit.dev~mirage/descr
- packages/datakit/datakit.dev~mirage/opam
- packages/datakit/datakit.dev~mirage/url
- packages/xenctrl/xenctrl.dev~mirage/descr
- packages/xenctrl/xenctrl.dev~mirage/opam
- packages/xenctrl/xenctrl.dev~mirage/url
> Xenctrl.dev

- packages/git/git.dev~mirage/opam
- packages/git/git.dev~mirage/url
change this to ocaml-git master when https://github.com/mirage/ocaml-git/pull/164 is merged
> point git at local branch w/connect changes

- packages/mirage-bootvar-solo5/mirage-bootvar-solo5.dev~mirage/opam
- packages/mirage-bootvar-xen/mirage-bootvar-xen.dev~mirage/opam
> now need parse-argv

- packages/conduit/conduit.dev~mirage/opam
- packages/conduit/conduit.dev~mirage/url
see https://github.com/mirage/ocaml-conduit/pull/158 (and the TLS change here https://github.com/mirleft/ocaml-tls/pull/336)
> use a fixed conduit

- .travis-ci.sh
- packages/logs-syslog/logs-syslog.dev~mirage/opam
- packages/logs-syslog/logs-syslog.dev~mirage/url
also built within travis-ci.sh
> logs-syslog for Mirage3

- packages/charrua-client/charrua-client.dev~mirage/descr
- packages/charrua-client/charrua-client.dev~mirage/opam
- packages/charrua-client/charrua-client.dev~mirage/url
should work now that V1_LWT.ipv4_config exists.
> add charrua-client

- packages/datakit-ci/datakit-ci.dev~mirage/opam
see https://github.com/docker/datakit/pull/319 .
> restrict datakit-ci to >= 4.03

- packages/mirage-console-solo5/mirage-console-solo5.dev~mirage/opam
look for travis in #196 instead, to be merged with https://github.com/mirage/mirage-console-solo5/pull/4 [good to merge!]
> mirage-console-solo5 adjust opam

- packages/mirage-net-solo5/mirage-net-solo5.dev~mirage/opam
> sync with upstream

- packages/mirage-solo5/mirage-solo5.dev~mirage/opam
- packages/ocb-stubblr/ocb-stubblr.dev~mirage/descr
- packages/ocb-stubblr/ocb-stubblr.dev~mirage/opam
- packages/ocb-stubblr/ocb-stubblr.dev~mirage/url
this is for https://github.com/mirage/mirage-solo5/pull/15 once https://github.com/mirage/mirage/pull/669 is in
> add stubblr, update mirage-solo5 metadata

- packages/mirage-block-solo5/mirage-block-solo5.dev~mirage/opam
For mirage/mirage-block-solo5#5.
> Update mirage-block-solo5 metadata

- packages/qcow-format/qcow-format.dev~mirage/url
now that mirage/ocaml-qcow#27 has been merged
> fix qcow url

- packages/qcow-format/qcow-format.dev~mirage/url
Unfortunately a little more work has to be done in master and released
before the Mirage 3 release.
Signed-off-by: David Scott <dave@recoil.org>
> Point qcow-format at the mirage-dev branch

- packages/hvsock/hvsock.dev~mirage/url
see mirage/ocaml-hvsock#41 for the merge to master
> hvsock: point to the mirage-dev branch

- packages/nbd/nbd.dev~mirage/url
> Revert "switch nbd to master branch now that patches are merged"

- packages/irmin/irmin.dev~mirage/opam
- packages/mirage-irmin/mirage-irmin.dev~mirage/descr
- packages/mirage-irmin/mirage-irmin.dev~mirage/opam
this attemps to fix https://github.com/mirage/irmin/issues/388
//cc @samoht
> add mirage-irmin.dev~mirage

- packages/fat-filesystem/fat-filesystem.dev~mirage/url
Note this won't build unless https://github.com/mirage/mirage/pull/733 is merged first.
> Add fat-filesystem mirage-dev

- packages/mirage-types-lwt/mirage-types-lwt.dev~mirage/opam
- packages/mirage-types/mirage-types.dev~mirage/opam
https://github.com/mirage/mirage/pull/735
> adjust mirage-types and mirage-types-lwt

- packages/dns/dns.dev~mirage/opam
> dns: require mirage-types-lwt

- packages/arp/arp.dev~mirage/opam
- packages/channel/channel.dev~mirage/opam
- packages/charrua-client/charrua-client.dev~mirage/opam
- packages/fat-filesystem/fat-filesystem.dev~mirage/opam
- packages/github/github.dev~mirage/opam
- packages/hvsock/hvsock.dev~mirage/opam
- packages/mirage-clock-freestanding/mirage-clock-freestanding.dev~mirage/opam
- packages/mirage-console-solo5/mirage-console-solo5.dev~mirage/opam
- packages/mirage-console-xen-cli/mirage-console-xen-cli.dev~mirage/opam
- packages/mirage-console-xen-proto/mirage-console-xen-proto.dev~mirage/opam
- packages/mirage-entropy/mirage-entropy.dev~mirage/opam
- packages/mirage-flow/mirage-flow.dev~mirage/opam
- packages/mirage-net-solo5/mirage-net-solo5.dev~mirage/opam
- packages/mirage-stdlib-random/mirage-stdlib-random.dev~mirage/opam
- packages/mirage-vnetif/mirage-vnetif.dev~mirage/opam
- packages/nbd/nbd.dev~mirage/opam
- packages/nocrypto/nocrypto.dev~mirage/opam
- packages/xenctrl/xenctrl.dev~mirage/opam
```
for packages in mirage-dev; do
if opam in upstream has a newer commit time; then
take that one
fi
done | human-brain
```
> attempt to pull recent changes from upstream

- packages/charrua-core/charrua-core.dev~mirage/opam
- packages/mirage-block/mirage-block.dev~mirage/opam
- packages/mirage-logs/mirage-logs.dev~mirage/opam
- packages/mirage-net-unix/mirage-net-unix.dev~mirage/opam
- packages/mirage-qubes/mirage-qubes.dev~mirage/opam
- packages/protocol-9p/protocol-9p.dev~mirage/opam
The same changes will be requested in the repositories for each of these packages.
> Unify opams

- packages/mirage-block-ccm/mirage-block-ccm.dev~mirage/url
- packages/session/session.dev~mirage/descr
- packages/session/session.dev~mirage/findlib
- packages/session/session.dev~mirage/opam
- packages/session/session.dev~mirage/url
thanks @hannesm for pointing out mirage-block-ccm fix
> let datakit-ci build again and fix mirage-block-ccm

- packages/logs-syslog/logs-syslog.dev~mirage/opam
- packages/tls/tls.dev~mirage/opam
- packages/tls/tls.dev~mirage/url
travis likes this https://travis-ci.org/hannesm/mirage-dev/builds/186411914
> use tls from master, opam fixes

- packages/charrua-core/charrua-core.dev~mirage/opam
- packages/dns/dns.dev~mirage/opam
- packages/mirage-block-ccm/mirage-block-ccm.dev~mirage/opam
- packages/mirage-channel/mirage-channel-lwt.dev~mirage/opam
- packages/mirage-channel/mirage-channel.dev~mirage/opam
- packages/mirage-clock/mirage-clock-freestanding.dev~mirage/opam
- packages/mirage-clock/mirage-clock-lwt.1.2.0/opam
- packages/mirage-clock/mirage-clock-unix.dev~mirage/opam
- packages/mirage-clock/mirage-clock.1.2.0/opam
- packages/mirage-console/mirage-console-lwt.2.2.0/opam
- packages/mirage-console/mirage-console-unix.dev~mirage/opam
- packages/mirage-console/mirage-console-xen-backend.dev~mirage/opam
- packages/mirage-console/mirage-console-xen-cli.dev~mirage/opam
- packages/mirage-console/mirage-console-xen-proto.dev~mirage/opam
- packages/mirage-console/mirage-console-xen.dev~mirage/opam
- packages/mirage-console/mirage-console.2.2.0/opam
- packages/mirage-net/mirage-net-lwt.1.0.0/opam
- packages/mirage-net/mirage-net.1.0.0/opam
- packages/mirage-protocols-lwt/mirage-protocols-lwt.dev~mirage/opam
- packages/mirage-protocols/mirage-protocols.dev~mirage/opam
- packages/mirage-random/mirage-random.dev~mirage/opam
- packages/mirage-runtime/mirage-runtime.dev~mirage/opam
- packages/mirage-stack-lwt/mirage-stack-lwt.dev~mirage/opam
- packages/mirage-stack/mirage-stack.dev~mirage/opam
- packages/mirage-time-lwt/mirage-time-lwt.dev~mirage/opam
- packages/mirage-time/mirage-time.dev~mirage/opam
- packages/mirage-types-lwt/mirage-types-lwt.dev~mirage/opam
- packages/mirage-types/mirage-types.dev~mirage/opam
> sync mainly topkg>=0.8.0 constraints, but other things as well

- packages/mirage-block-xen/mirage-block-xen.dev~mirage/opam
- packages/mirage-fs/mirage-fs-lwt.1.0.0/opam
- packages/mirage-kv-lwt/mirage-kv-lwt.1.0.0/opam
- packages/mirage-kv/mirage-kv.1.0.0/opam
see https://github.com/mirage/mirage-kv/pull/4 and https://github.com/mirage/mirage-fs/pull/12
> fix mirage-kv{-lwt} opam files from upstream

- packages/logs-syslog/logs-syslog.dev~mirage/opam
> sync opam for logs-syslog

- packages/datakit/datakit.dev~mirage/url
see https://github.com/docker/datakit/pull/433 for upstream
PR
> datakit: point to working mirage-dev branch

- .travis-ci.sh
- packages/datakit-ci/datakit-ci.dev~mirage/opam
- packages/datakit-client/datakit-client.dev~mirage/datakit-client.opam
- packages/datakit-client/datakit-client.dev~mirage/descr
- packages/datakit-client/datakit-client.dev~mirage/opam
- packages/datakit-client/datakit-client.dev~mirage/url
- packages/datakit-server/datakit-server.dev~mirage/descr
- packages/datakit-server/datakit-server.dev~mirage/opam
- packages/datakit-server/datakit-server.dev~mirage/url
- packages/datakit/datakit.dev~mirage/opam
- packages/datakit/datakit.dev~mirage/url
fix the conflict I introduced in #330  (sorry @avsm) and add lower bound for mirage-channel
> Prom channel

- packages/mirage-crypto-pk/mirage-crypto-pk.0.10.1/opam
> Add a constraint about zarith/mirage.4.0.0 on mirage-crypto-pk.0.10.1

- packages/mirage/mirage.4.0.0/opam
> Update mirage.4.0.0 to really use the latest version

- packages/mirage/mirage.4.0.0/opam
> Update opam file of mirage to require functoria.4.0.0

- packages/functoria/functoria.4.0.0/opam
- packages/mirage-block-solo5/mirage-block-solo5.0.6.2/opam
- packages/mirage-block-xen/mirage-block-xen.2.1.0/opam
- packages/mirage-console-xen-backend/mirage-console-xen-backend.5.1.0/opam
- packages/mirage-console-xen-proto/mirage-console-xen-proto.5.1.0/opam
- packages/mirage-console-xen/mirage-console-xen.5.1.0/opam
- packages/mirage-net-solo5/mirage-net-solo5.0.6.3/opam
- packages/mirage-net-xen/mirage-net-xen.2.1.0/opam
- packages/mirage-solo5/mirage-solo5.0.7.0/opam
- packages/mirage-unix/mirage-unix.5.0.0/opam
- packages/mirage-xen/mirage-xen.7.0.0/opam
- packages/mirage/mirage.4.0.0/opam
- packages/netchannel/netchannel.2.1.0/opam
See:
- mirage/mirage-unix#19
- mirage/mirage-xen#38
- mirage/mirage-solo5#83
- and mirage/mirage#1269
> No common OS module

- packages/ocaml-solo5/ocaml-solo5.0.8.0/opam
see mirage/ocaml-freestanding#114
> Add ocaml-solo5.0.8.0
