packages/asn1-combinators/asn1-combinators.0.1.2/descr
packages/asn1-combinators/asn1-combinators.0.1.2/opam
packages/asn1-combinators/asn1-combinators.0.1.2/url
packages/mirage-entropy-xen/mirage-entropy-xen.0.3.0/descr
packages/mirage-entropy-xen/mirage-entropy-xen.0.3.0/opam
packages/mirage-entropy-xen/mirage-entropy-xen.0.3.0/url
packages/nocrypto/nocrypto.0.4.0/descr
packages/nocrypto/nocrypto.0.4.0/opam
packages/nocrypto/nocrypto.0.4.0/url
packages/tls/tls.0.5.0/descr
packages/tls/tls.0.5.0/opam
packages/tls/tls.0.5.0/url
packages/x509/x509.0.3.1/descr
packages/x509/x509.0.3.1/opam
packages/x509/x509.0.3.1/url

this is not being released to the main opam-repository yet since it might break stuff partially...
it awaits for: https://github.com/mirage/mirage/pull/394 and a solution for zarith & gmp (maybe https://github.com/mirage/mirage-dev/pull/63 is a start?)

add asn1/mirage-entropy-xen/nocrypto/tls/x509 which might work out of the box

---

packages/asn1-combinators/asn1-combinators.0.1.2/opam
packages/gmp-xen/gmp-xen.6.0.0/files/META
packages/gmp-xen/gmp-xen.6.0.0/files/gmp-xen.pc
packages/gmp-xen/gmp-xen.6.0.0/files/mirage-build.sh
packages/gmp-xen/gmp-xen.6.0.0/files/mirage-install.sh
packages/gmp-xen/gmp-xen.6.0.0/opam
packages/jitsu/jitsu.0.1/opam
packages/mirage-entropy-xen/mirage-entropy-xen.0.3.0/opam
packages/mirage-nat/mirage-nat.0.2/opam
packages/mirage-profile/mirage-profile.0.1/opam
packages/mirage-vnetif/mirage-vnetif.0.1/opam
packages/nocrypto/nocrypto.0.4.0/opam
packages/tls/tls.0.5.0/opam
packages/x509/x509.0.3.1/opam
packages/zarith/zarith.1.3/files/mirage-install.sh
packages/zarith/zarith.1.3/files/xen_linkopts.patch

I've changed a little bit how we do things, using `ocamlfind` to handle the overlay C dependencies was not a so good idea. The current `xen_linkopts` scheme is not very satisfactory, but well, it works...

Fix gmp-xen

---

packages/gmp-xen/gmp-xen.6.0.0/files/mirage-build.sh
packages/gmp-xen/gmp-xen.6.0.0/opam

on cstruct etc., whereas gmp-xen only needs some CFLAGS and include
files. minimizes recompilations

depend on mirage-xen-posix, instead of mirage-xen. the latter depends

---

.travis.yml

this was disabled in October 2014, but mirage-xen works with ocaml 4.2 since 2.2.0, thus re-enabling

also build on 4.02

---

packages/gmp-xen/gmp-xen.6.0.0/files/mirage-build.sh

GMP contains specific support for about a dozen generations per cpu architecture, but normally only compiles in what was detected as the target platform via `config.guess`. On x86 and x86_64, it can instead be compiled with all the generations and a cpu-detection shim.
The effect is to bump the `.a` from 1.2MB to 1.4MB. I didn't measure the performance hit, but at some point in the past I found it to be about 15% for mildly divergent build vs. run machines.

gmp: build cpu autodetection

---

.travis-ci.sh

since master is supposed to work with opam-repository, and mirage-dev branch with this mirage-dev opam repository...

use mirage-dev branch of mirage-skeleton

---

packages/mirage-clock-unix/mirage-clock-unix.dev~mirage/opam
packages/mirage-clock-unix/mirage-clock-unix.dev~mirage/url
packages/mirage-clock-xen/mirage-clock-xen.dev~mirage/opam
packages/mirage-clock-xen/mirage-clock-xen.dev~mirage/url
packages/mirage-flow/mirage-flow.dev~mirage/opam
packages/mirage-flow/mirage-flow.dev~mirage/url
packages/mirage-logs/mirage-logs.dev~mirage/opam
packages/mirage-logs/mirage-logs.dev~mirage/url

These pins are needed to build now that V1.CLOCK is no more.

Include packages that needed CLOCK API updates.

---

.travis-ci.sh
.travis.yml

- Use ocaml-travisci-skeleton/travis-ocaml.sh instead of custom script.
- Run on Ubuntu Trusty (14.04). 12.04 is ancient and mirage-dev is
supposed to be a testbed for "latest master".
- Add Solo5 targets (ukvm, virtio).
- Add Ocaml 4.03.0.

Travis updates (skeleton script, use trusty, add Solo5)

---

packages/fat-filesystem/fat-filesystem.0.11.0/descr
packages/fat-filesystem/fat-filesystem.0.11.0/findlib
packages/fat-filesystem/fat-filesystem.0.11.0/opam
packages/fat-filesystem/fat-filesystem.0.11.0/url

(can be removed once this is merged into opam-repository, see https://github.com/ocaml/opam-repository/pull/7399 )

fat-filesystem version 11 

---

packages/mirage-logs/mirage-logs.dev~mirage/opam

current mirage-logs master has an updated opam file; sync to make installable again

update opam file for mirage-logs

---

packages/fat-filesystem/fat-filesystem.dev~mirage/opam
packages/irmin/irmin.dev~mirage/url
packages/protocol-9p/protocol-9p.dev~mirage/opam
packages/protocol-9p/protocol-9p.dev~mirage/url

add `rresult` to `fat-filesystem` dependencies, use the `mem-in-kvro` branch for Irmin, and use the current master of `protocol-9p`.

KV_RO mem changes

---

packages/mirage/mirage.dev~mirage/opam

got this error while trying to install mirage 
```
pkg.ml: [ERROR] key --pinned: No value specified
```

fix opam file typo

---

packages/nbd/nbd.dev~mirage/opam
packages/nbd/nbd.dev~mirage/url
packages/qcow/qcow.dev~mirage/opam
packages/qcow/qcow.dev~mirage/url

maybe the doc build works with this branch @avsm 
`opam remote add extra https://github.com/hannesm/mirage-dev.git#qcow` should do the trick
includes https://github.com/mirage/ocaml-qcow/pull/27 and https://github.com/xapi-project/nbd/pull/28

add my qcow and nbd branches

---

packages/git/git.dev~mirage/url

This is so I can still release bug-fixes of ocaml-git without having to
release MirageOS3 first.

Use a branch of ocaml-git as url

---

packages/mirage-bootvar-xen/mirage-bootvar-xen.dev~mirage/opam

See https://github.com/mirage/mirage-bootvar-xen/pull/29 .

update opam for mirage-bootvar-xen

---

packages/mirage-net-unix/mirage-net-unix.dev~mirage/opam

mirage-net-unix's `.travis.yml` specifies that the tests need to be run as root, but that (obviously) doesn't get inherited by other procedures that are running the tests as a side effect of `opam install -t` (see https://travis-ci.org/mirage/mirage/jobs/171098959 for an example).  For now, remove the `build-test` instructions for mirage-net-unix in mirage-dev.

remove build-test from mirage-net-unix for now

---

packages/cpuid/cpuid.dev~mirage/descr
packages/cpuid/cpuid.dev~mirage/opam
packages/cpuid/cpuid.dev~mirage/url
packages/mirage-entropy/mirage-entropy.dev~mirage/descr
packages/mirage-entropy/mirage-entropy.dev~mirage/opam
packages/mirage-entropy/mirage-entropy.dev~mirage/url
packages/mirage-os-shim/mirage-os-shim.dev~mirage/descr
packages/mirage-os-shim/mirage-os-shim.dev~mirage/opam
packages/mirage-os-shim/mirage-os-shim.dev~mirage/url
packages/nocrypto/nocrypto.dev~mirage/opam
packages/nocrypto/nocrypto.dev~mirage/url
packages/ocb-stubblr/ocb-stubblr.dev~mirage/descr
packages/ocb-stubblr/ocb-stubblr.dev~mirage/opam
packages/ocb-stubblr/ocb-stubblr.dev~mirage/url

I was far, far too quick to release bits of this in the main repo, in hopes of avoiding dev pins for the supporting libs.
Turns out, the entire set of changes had variously wrong version constraints, and even some bad `META`s floating around. :sob: 
Versions in this PR should work well together.
Note that it introduces yet another entropy package, `mirage-entropy`. That one obsoletes `mirage-entropy-xen` and `mirage-entropy-solo5`. If, by coincidence, this PR turns out to work, various tests floating around must remove `mirage-entropy-xen` from the list of packages they install.

Update crypto and everything around it

---

packages/hvsock/hvsock.dev~mirage/url

Related to [mirage/ocaml-hvsock#33]
Signed-off-by: David Scott <dave@recoil.org>

hvsock: point at mirage/ocaml-hvsock rather than avsm/ocaml-hvsock

---

.travis.yml

Once core dependencies (`ipaddr` and others which rely on `janestreet` libraries, at a minimum) are buildable on 4.04, we should begin testing that compiler instead.

Don't test on 4.02 for the set of packages included in Mirage 3.

---

packages/ocaml-freestanding/ocaml-freestanding.dev~mirage/opam

@hannesm @yomimono This enables Solo5 targets on 4.04.0. We should probably add 4.04.0 to the various Travis builds, but I'll leave that to you (not sure what limitations on the # of builds we have).

ocaml-freestanding: Sync OPAM (4.04 support)

---

packages/mirage-clock-freestanding/mirage-clock-freestanding.dev~mirage/opam
packages/mirage-clock-freestanding/mirage-clock-freestanding.dev~mirage/url

Depends on mirage/mirage-clock#21, mirage/mirage#684.
`mirage-clock-xen` will be removed in a separate PR once this goes in.

Add mirage-clock-freestanding

---

.travis-ci.sh

this should not be needed, and since I introduced a `build` phase (in functoria + mirage), it is no longer

not needed

---

packages/dns/dns.dev~mirage/opam
packages/mirage-clock-unix/mirage-clock-unix.dev~mirage/opam
packages/mirage-flow/mirage-flow.dev~mirage/opam
packages/mirage-vnetif/mirage-vnetif.dev~mirage/opam

These should probably be reported upstream too.

Add missing constraint to mirage-types>=3.0.0

---

packages/conduit/conduit.dev~mirage/opam

conflicts with version less than x are commonly really depopt version dependencies; these should be automatically updated too, but in the meantime here's one I noticed.

conduit conflicts w/mirage-types < 3

---

packages/channel/channel.dev~mirage/opam
packages/crunch/crunch.dev~mirage/opam
packages/datakit/datakit.dev~mirage/opam
packages/git-mirage/git-mirage.dev~mirage/opam
packages/git/git.dev~mirage/opam
packages/irmin-mirage/irmin-mirage.dev~mirage/opam
packages/mirage-block-ccm/mirage-block-ccm.dev~mirage/opam
packages/mirage-block-ramdisk/mirage-block-ramdisk.dev~mirage/opam
packages/mirage-block/mirage-block.dev~mirage/opam
packages/mirage-clock-freestanding/mirage-clock-freestanding.dev~mirage/opam
packages/mirage-clock-unix/mirage-clock-unix.dev~mirage/opam
packages/mirage-console-solo5/mirage-console-solo5.dev~mirage/opam
packages/mirage-console-xen/mirage-console-xen.dev~mirage/opam
packages/mirage-flow/mirage-flow.dev~mirage/opam
packages/mirage-fs-unix/mirage-fs-unix.dev~mirage/opam
packages/mirage-net-macosx/mirage-net-macosx.dev~mirage/opam
packages/mirage-net-solo5/mirage-net-solo5.dev~mirage/opam
packages/mirage-qubes/mirage-qubes.dev~mirage/opam
packages/mirage-runtime/mirage-runtime.dev~mirage/opam
packages/mirage-stdlib-random/mirage-stdlib-random.dev~mirage/opam
packages/protocol-9p/protocol-9p.dev~mirage/opam
packages/qcow-format/qcow-format.dev~mirage/opam
packages/shared-block-ring/shared-block-ring.dev~mirage/opam
packages/tar-format/tar-format.dev~mirage/opam
packages/vchan/vchan.dev~mirage/opam
packages/vhd-format/vhd-format.dev~mirage/opam

superseed #246
It's not perfect but it is less intrusive.

automatically add {>= 3.0.0} version constraints for mirage-types{-lwt}

---

packages/functoria-runtime/functoria-runtime.dev~mirage/opam

Incidentally this should unbreak 4.02 testing for packages relying on `mirage-runtime` for printers.

sync functoria opam

---

packages/mirage-random/mirage-random.dev~mirage/opam

opam v2 seems to select an older cstruct and fail sometimes

depend on cstruct>="1.9" in mirage-random

---

packages/mirage-runtime/mirage-runtime.dev~mirage/opam
packages/mirage/mirage.dev~mirage/opam

otherwise on 4.02.3, mirage-runtime can pull in mirage-2.8.0
break

constraint runtime to a modern version of mirage-types

---

packages/functoria-runtime/functoria-runtime.dev~mirage/opam
packages/functoria/functoria.dev~mirage/opam
packages/git-http/git-http.2.0.0/opam
packages/git-mirage/git-mirage.2.0.0/opam
packages/git-unix/git-unix.2.0.0/opam
packages/git/git.2.0.0/opam
packages/hvsock/hvsock.dev~mirage/opam
packages/irmin-git/irmin-git.1.0.0/opam
packages/irmin-http/irmin-http.1.0.0/opam
packages/irmin-mirage/irmin-mirage.1.0.0/opam
packages/mirage-block-lwt/mirage-block-lwt.1.0.0/opam
packages/mirage-block-unix/mirage-block-unix.dev~mirage/opam
packages/mirage-block/mirage-block.1.0.0/opam
packages/mirage-dns/mirage-dns.dev~mirage/opam
packages/mirage-http/mirage-http.dev~mirage/opam
packages/mirage-net-macosx/mirage-net-macosx.dev~mirage/opam
packages/mirage-net-solo5/mirage-net-solo5.dev~mirage/opam
packages/mirage-net-xen/mirage-net-xen.dev~mirage/opam
packages/mirage-qubes/mirage-qubes.dev~mirage/opam
packages/mirage-solo5/mirage-solo5.dev~mirage/opam
packages/mirage-stdlib-random/mirage-stdlib-random.dev~mirage/opam
packages/mirage-unix/mirage-unix.dev~mirage/opam
packages/mirage-vnetif/mirage-vnetif.dev~mirage/opam
packages/mirage-www/mirage-www.dev~mirage/opam
packages/mirage-xen-ocaml/mirage-xen-ocaml.dev~mirage/opam
packages/mirage-xen/mirage-xen.dev~mirage/opam
packages/protocol-9p/protocol-9p.dev~mirage/opam
packages/vchan/vchan.dev~mirage/opam

added via opam-tagger in https://github.com/avsm/opam-tagger
this should be mainly mirage-core packages, @yomimono

add org:mirage tag to mirage libraries

---

packages/hvsock/hvsock.dev~mirage/opam

hvsock: sync with upstream hvsock opam file in mirage-dev

---

packages/charrua-core/charrua-core.dev~mirage/opam

I suspect the one in mirageos-3-beta needs to stay as is since it refers to 0.4 tarball

merge charrua-core.opam from upstream (topkg'ed)

---

Dockerfile

This reproduces the recent `tls.lwt` issue. Ideally we would have some tool which parses (or generates) the `.travis.yml` and this `Dockerfile` to keep them in sync.
Signed-off-by: David Scott <dave@recoil.org>

Add a Dockerfile to reproduce a travis build

---

packages/mirage-protocols-lwt/mirage-protocols-lwt.1.3.0/opam
packages/mirage-protocols-lwt/mirage-protocols-lwt.1.3.0/url
packages/mirage-protocols/mirage-protocols.1.3.0/opam
packages/mirage-protocols/mirage-protocols.1.3.0/url
packages/mirage-stack-lwt/mirage-stack-lwt.1.2.0/opam
packages/mirage-stack-lwt/mirage-stack-lwt.1.2.0/url
packages/mirage-stack/mirage-stack.1.2.0/opam
packages/mirage-stack/mirage-stack.1.2.0/url
packages/tcpip/tcpip.3.4.0/opam
packages/tcpip/tcpip.3.4.0/url
packages/vpnkit/vpnkit.0.2.0/opam
packages/vpnkit/vpnkit.0.2.0/url

See [mirage/mirage-protocols#8]
This will allow the CI to test the interface change properly before we merge/release.
Signed-off-by: David Scott <dave@recoil.org>

Add packages affected by keepalives

---

packages/functoria-runtime/functoria-runtime.4.0.0/opam
packages/functoria/functoria.4.0.0/opam
packages/mirage-runtime/mirage-runtime.4.0.0/opam
packages/mirage-solo5/mirage-solo5.0.7.0/opam
packages/mirage-xen/mirage-xen.7.0.0/opam

this is basically what we applied to mirage-crypto-pk as well, otherwise a unikernel will depend on mirage+friends

mirage-solo5: depend on mirage-runtime, not mirage

---

packages/base/base.v0.14.2/opam

`base.v0.14.2` was released to support OCaml 4.14.0 (https://github.com/janestreet/base/pull/124). As a consequence the fork needed to be rebased to take that change into account.

Update base fork to v0.14.2

---

packages/digestif/digestif.1.1.1/opam
packages/mirage-block-solo5/mirage-block-solo5.0.8.0/opam
packages/mirage-bootvar-solo5/mirage-bootvar-solo5.0.6.0/opam
packages/mirage-clock-solo5/mirage-clock-solo5.4.2.0/opam
packages/mirage-clock-unix/mirage-clock-unix.4.2.0/opam
packages/mirage-clock/mirage-clock.4.2.0/opam
packages/mirage-console-solo5/mirage-console-solo5.0.8.0/opam
packages/mirage-net-solo5/mirage-net-solo5.0.8.0/opam
packages/mirage-solo5/mirage-solo5.0.8.0/opam
packages/mirage-xen/mirage-xen.7.1.0/opam

https://github.com/mirage/mirage-solo5/pull/85
https://github.com/mirage/mirage-net-solo5/pull/43
https://github.com/mirage/mirage-block-solo5/pull/24
https://github.com/mirage/mirage-console-solo5/pull/23
https://github.com/mirage/mirage-clock/pull/52
https://github.com/mirage/mirage-xen/pull/40

Rename the freestanding context to solo5 for mirage-{console,net,block}-solo5
